### ISSUE TITLE
Export code coverage

### ISSUE THREAD

**Issue by bhcrosslake** [mojaloop/central-hub#7]
the central-hub code has tests, but the code coverage is not being exported to SonarQube
The tests should create a lcov.info file and copy it to S3 for pickup
- aws s3 cp ./coverage/lcov.info s3://elasticbeanstalk-us-west-2-886403637725/sonar/central-hub/

**Comment by mdebarros** [comment]
Hey @bhcrosslake 

That has been completed with the following
Feature: https://app.zenhub.com/workspace/o/mojaloop/project/issues/81
PR: https://github.com/mojaloop/central-hub/pull/9

**Comment by mdebarros** [comment]
Closing this issue since it has been resolved.

**Comment by mdebarros** [comment]
Issue has been tested and fixed with:
Feature: https://app.zenhub.com/workspace/o/mojaloop/project/issues/81
PR: #9
